site_name: "European Environment for Scientific Software Installations (EESSI)"
site_url: https://eessi.github.io/docs/
google_analytics:
    - UA-169665333-1
    - auto
theme:
  name: material
  features:
    - instant
    - tabs
  logo: img/logos/EESSI.png
  favicon: img/logos/EESSI.png
repo_name: EESSI @ GitHub
repo_url: https://github.com/EESSI
edit_uri: docs/edit/master/docs
nav:
  - Home: index.md
  - Project overview: overview.md
  - Filesystem layer: filesystem_layer.md
  - Compatibility layer: compatibility_layer.md
  - Software layer: software_layer.md
  - Project partners: partners.md
  - Contact info: contact.md
plugins:
  # show revision date at bottom of each page
  - git-revision-date-localized
  # necessary for search to work
  - search
markdown_extensions:
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences
  # tabbed contents
  - pymdownx.tabbed
  - toc:
      permalink: true
extra:
  # add links in bottom right
  social:
    - type: github
      icon: octicons/logo-github
      link: https://github.com/EESSI
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eessi_hpc
